version: '3'

services:
  tcc8985_develop:
    container_name: tcc8985_develop
#    image: 192.168.27.12:5000/pub-tcc8985:latest
    image: dev-tcc8985:latest
    command: /usr/sbin/sshd -D
    ports:
      - "9022:22"
    expose:
      - '9022'
    stdin_open: true
    volumes:
      - '/home/lchy0113:/home/lchy0113'
      - '/etc/localtime:/etc/localtime'
    privileged: true
    networks:
      PRIV_network:
        ipv4_address : 172.22.0.7

  a40i_develop:
    container_name: a40i_develop
#    image: 192.168.27.12:5000/a40i:latest
    image: dev-a40i:latest
    command: /usr/sbin/sshd -D
    ports:
      - "9023:22"
    expose:
      - "9023"
    stdin_open: true
    volumes:
      - '/home/lchy0113/Develop/Allwinner:/home/lchy0113/Develop/Allwinner'
      - '/dev/bus/usb:/dev/bus/usb'
      - '/etc/localtime:/etc/localtime'
    privileged: true
    networks:
      PRIV_network:
        ipv4_address : 172.22.0.13

  nxp_develop:
    container_name: nxp_develop
#    image: 192.168.27.12:5000/pub-nxp:latest
    image: dev-nxp:latest
    command: /usr/sbin/sshd -D
    ports:
      - "9024:22"
    expose:
      - '9024'
    stdin_open: true
    volumes:
      - '/home/lchy0113:/home/lchy0113'
      - '/etc/localtime:/etc/localtime'
    privileged: true
    networks:
      PRIV_network:
        ipv4_address : 172.22.0.8

  qemu_develop:
    container_name: qemu_develop
    image: test-qemu:latest
    command: /usr/sbin/sshd -D
    ports:
      - "9025:22"
    expose:
      - '9025'
    stdin_open: true
    volumes:
      - '/home/lchy0113:/home/lchy0113'
      - '/etc/localtime:/etc/localtime'
    privileged: true
    networks:
      PRIV_network:
        ipv4_address : 172.22.0.9

  rk3568_develop:
    container_name: rk3568_develop
    image: dev-rk3568:latest
    command: /usr/sbin/sshd -D
    ports:
      - "9026:22"
    expose:
      - '9026'
    stdin_open: true
    volumes:
      - '/home/lchy0113:/home/lchy0113'
      - '/etc/localtime:/etc/localtime'
    privileged: true
    networks:
      PRIV_network:
        ipv4_address : 172.22.0.10

  i386_develop:
    container_name: i386_develop
    image: ubuntu16_04_i386_slave:latest
    command: /bin/bash
    ports:
      - "9024:22"
    environment:
      - TZ=Asia/Seoul
    expose:
      - "9024"
    stdin_open: true
    volumes:
      - '/home/lchy0113:/home/lchy0113'
      - '/dev/bus/usb:/dev/bus/usb'
      - '/etc/localtime:/etc/localtime'
    privileged: true
    networks:
      PRIV_network:
        ipv4_address : 172.22.0.14

networks:
  PRIV_network:
    ipam:
      driver: default
      config: 
        - subnet: 172.22.0.0/16
 
